{{- if .Values.websocket.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dorgu-operator.fullname" . }}-websocket
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dorgu-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.websocket.service.type }}
  ports:
    - port: {{ .Values.websocket.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "dorgu-operator.selectorLabels" . | nindent 4 }}
{{- end }}
